#!/usr/bin/env python3
"""
Analyze video quality and generate refinement recommendations for next render pass.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict

from video_quality_utils import (
    clamp,
    measure_loudness,
    probe_video,
    sample_frame_luma,
    summarize_metrics,
)


def recommend(metrics: Dict[str, float]) -> Dict[str, float]:
    mean_luma = metrics.get("mean_luma", 0.0)
    std_luma = metrics.get("std_luma", 0.0)
    loudness_i = metrics.get("input_i", -20.0)
    size_mb = metrics.get("size_mb", 0.0)

    map_brightness = 1.0
    if mean_luma < 9.0:
        map_brightness = 1.0 + ((9.0 - mean_luma) / 24.0)
    elif mean_luma > 26.0:
        map_brightness = 1.0 - ((mean_luma - 26.0) / 36.0)
    map_brightness = clamp(map_brightness, 0.85, 1.25)

    text_alpha_scale = 1.0
    route_glow_scale = 1.0
    if std_luma < 7.0:
        text_alpha_scale = 1.20
        route_glow_scale = 1.15
    elif std_luma > 24.0:
        text_alpha_scale = 0.93

    voice_gain = 1.0
    music_gain = 0.30
    if loudness_i < -16.5:
        voice_gain = 1.12
        music_gain = 0.28
    elif loudness_i > -13.0:
        voice_gain = 0.92
        music_gain = 0.24

    render_crf = 20.0
    if size_mb < 4.2:
        render_crf = 18.0
    elif size_mb > 18:
        render_crf = 21.0

    return {
        "DOC_MAP_BRIGHTNESS": round(map_brightness, 3),
        "DOC_TEXT_ALPHA_SCALE": round(text_alpha_scale, 3),
        "DOC_ROUTE_GLOW_SCALE": round(route_glow_scale, 3),
        "DOC_VOICE_GAIN": round(voice_gain, 3),
        "DOC_MUSIC_GAIN": round(music_gain, 3),
        "DOC_RENDER_CRF": int(render_crf),
    }


def write_env_file(path: Path, values: Dict[str, float]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f'{key}="{value}"' for key, value in values.items()]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze video and suggest refinement env vars.")
    parser.add_argument("--video", required=True, help="Input video path")
    parser.add_argument("--report", required=True, help="Output report JSON path")
    parser.add_argument("--env-output", required=True, help="Output env file path")
    args = parser.parse_args()

    video_path = Path(args.video).resolve()
    if not video_path.exists():
        raise FileNotFoundError(f"Video not found: {video_path}")

    probe = probe_video(video_path)
    loudness = measure_loudness(video_path)
    luma = sample_frame_luma(video_path, every_seconds=10, max_frames=18)
    metrics = summarize_metrics(probe, loudness, luma)
    suggestions = recommend(metrics)

    report = {
        "video": str(video_path),
        "metrics": metrics,
        "suggestions": suggestions,
        "notes": [
            "Suggestions are generated by rule-based AI quality heuristics.",
            "Apply suggested env vars before refined render pass.",
        ],
    }

    report_path = Path(args.report).resolve()
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    write_env_file(Path(args.env_output).resolve(), suggestions)

    print("[analysis] quality_score:", metrics.get("quality_score"))
    print("[analysis] loudness_i:", metrics.get("input_i"))
    print("[analysis] mean_luma:", metrics.get("mean_luma"))
    print("[analysis] suggestions:", suggestions)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
