#!/usr/bin/env python3
"""
Analyze video quality and generate refinement recommendations for next render pass.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict

from video_quality_utils import (
    clamp,
    measure_loudness,
    probe_video,
    sample_frame_luma,
    sample_motion_energy,
    sample_warm_ratio,
    summarize_metrics,
)


def recommend(metrics: Dict[str, float]) -> Dict[str, float]:
    mean_luma = metrics.get("mean_luma", 0.0)
    std_luma = metrics.get("std_luma", 0.0)
    loudness_i = metrics.get("input_i", -20.0)
    loudness_lra = metrics.get("input_lra", 0.0)
    size_mb = metrics.get("size_mb", 0.0)
    motion_mean = metrics.get("motion_mean", 0.0)
    warm_ratio = metrics.get("warm_ratio", 0.0)

    map_brightness = 1.0
    if mean_luma < 9.0:
        map_brightness = 1.0 + ((9.0 - mean_luma) / 24.0)
    elif mean_luma > 28.0:
        map_brightness = 1.0 - ((mean_luma - 28.0) / 40.0)
    map_brightness = clamp(map_brightness, 0.82, 1.30)

    text_alpha_scale = 1.0
    route_glow_scale = 1.0
    route_density_scale = 1.0
    missile_density_scale = 1.0
    shake_scale = 1.0
    bomber_count_scale = 1.0
    impact_ring_scale = 1.0
    target_circle_scale = 1.0
    grain_alpha = 38
    if std_luma < 7.0:
        text_alpha_scale = 1.25
        route_glow_scale = 1.20
        grain_alpha = 42
    elif std_luma > 26.0:
        text_alpha_scale = 0.90
        grain_alpha = 34

    if motion_mean < 7.5:
        route_density_scale = 1.22
        missile_density_scale = 1.28
        shake_scale = 1.25
        bomber_count_scale = 1.26
    elif motion_mean > 22.0:
        route_density_scale = 0.88
        missile_density_scale = 0.90
        shake_scale = 0.85

    if warm_ratio < 0.008:
        impact_ring_scale = 1.30
        target_circle_scale = 1.25
    elif warm_ratio > 0.050:
        impact_ring_scale = 0.88
        target_circle_scale = 0.88

    voice_gain = 1.08
    music_gain = 0.36
    sfx_gain = 0.28
    voice_energy = 1.30
    if loudness_i < -17.0:
        voice_gain = 1.18
        music_gain = 0.32
        sfx_gain = 0.32
        voice_energy = 1.40
    elif loudness_i > -12.5:
        voice_gain = 0.88
        music_gain = 0.28
        sfx_gain = 0.20
        voice_energy = 1.18

    if loudness_lra < 4.0:
        voice_energy = 1.42
    elif loudness_lra > 10.0:
        voice_energy = 1.12

    render_crf = 20.0
    if size_mb < 4.0:
        render_crf = 18.0
    elif size_mb > 20:
        render_crf = 22.0

    return {
        "DOC_MAP_BRIGHTNESS": round(map_brightness, 3),
        "DOC_TEXT_ALPHA_SCALE": round(text_alpha_scale, 3),
        "DOC_ROUTE_GLOW_SCALE": round(route_glow_scale, 3),
        "DOC_ROUTE_DENSITY_SCALE": round(clamp(route_density_scale, 0.70, 1.90), 3),
        "DOC_MISSILE_DENSITY_SCALE": round(clamp(missile_density_scale, 0.70, 2.40), 3),
        "DOC_SHAKE_SCALE": round(clamp(shake_scale, 0.0, 2.30), 3),
        "DOC_BOMBER_COUNT_SCALE": round(clamp(bomber_count_scale, 0.0, 2.50), 3),
        "DOC_IMPACT_RING_SCALE": round(clamp(impact_ring_scale, 0.65, 2.30), 3),
        "DOC_TARGET_CIRCLE_SCALE": round(clamp(target_circle_scale, 0.70, 1.95), 3),
        "DOC_GRAIN_ALPHA": int(clamp(grain_alpha, 25, 50)),
        "DOC_VOICE_GAIN": round(voice_gain, 3),
        "DOC_MUSIC_GAIN": round(music_gain, 3),
        "DOC_SFX_GAIN": round(sfx_gain, 3),
        "DOC_VOICE_ENERGY": round(voice_energy, 3),
        "DOC_RENDER_CRF": int(render_crf),
    }


def write_env_file(path: Path, values: Dict[str, float]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f'{key}="{value}"' for key, value in values.items()]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze video and suggest refinement env vars.")
    parser.add_argument("--video", required=True, help="Input video path")
    parser.add_argument("--report", required=True, help="Output report JSON path")
    parser.add_argument("--env-output", required=True, help="Output env file path")
    args = parser.parse_args()

    video_path = Path(args.video).resolve()
    if not video_path.exists():
        raise FileNotFoundError(f"Video not found: {video_path}")

    probe = probe_video(video_path)
    loudness = measure_loudness(video_path)
    luma = sample_frame_luma(video_path, every_seconds=10, max_frames=18)
    motion = sample_motion_energy(video_path, fps=1.2, max_frames=120)
    warmth = sample_warm_ratio(video_path, every_seconds=6, max_frames=24)
    metrics = summarize_metrics(probe, loudness, luma, motion=motion, warmth=warmth)
    suggestions = recommend(metrics)

    report = {
        "video": str(video_path),
        "metrics": metrics,
        "suggestions": suggestions,
        "notes": [
            "Suggestions are generated by rule-based AI quality heuristics.",
            "Apply suggested env vars before refined render pass.",
        ],
    }

    report_path = Path(args.report).resolve()
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    write_env_file(Path(args.env_output).resolve(), suggestions)

    print("[analysis] quality_score:", metrics.get("quality_score"))
    print("[analysis] loudness_i:", metrics.get("input_i"))
    print("[analysis] mean_luma:", metrics.get("mean_luma"))
    print("[analysis] suggestions:", suggestions)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
